import 'package:flutter/material.dart';

class Product {
  final String id, image, title, description, sponsor;
  final double price, size, rating;
  final Color color;
  final bool textDark;

  Product(
      {required this.id,
      required this.title,
      required this.image,
      required this.description,
      required this.color,
      required this.textDark,
      required this.price,
      required this.rating,
      required this.sponsor,
      required this.size});
}

List<Product> products = [
  Product(
    id: '89001',
    title: 'AIR JORDAN 1',
    image: 'assets/images/shop_01.png',
    description: 'AIR JORDAN 1 MID SE ELEPHANT PRINT',
    color: const Color.fromARGB(255, 143, 135, 135),
    textDark: false,
    price: 130.00,
    rating: 4.0,
    sponsor: 'assets/images/nba2.png',
    size: 20,
  ),
  Product(
    id: '89002',
    title: 'NIKE LEBRON 9',
    image: 'assets/images/shop_02.png',
    description: 'NIKE LEBRON 9 REGAL PINK QS',
    color: const Color.fromARGB(255, 255, 111, 238),
    textDark: true,
    price: 230.00,
    rating: 4.5,
    sponsor: 'assets/images/balle.png',
    size: 20,
  ),
  Product(
    id: '89003',
    title: 'AIR JORDAN 11',
    image: 'assets/images/shop_03.png',
    description: 'AIR JORDAN 11 CMFT LOW WHITE/UNIVERSITY RED',
    color: const Color.fromARGB(255, 41, 38, 38),
    textDark: false,
    price: 125.00,
    rating: 3.7,
    sponsor: 'assets/images/balle.png',
    size: 20,
  ),
  Product(
    id: '89004',
    title: 'AIR JORDAN LEGACY',
    image: 'assets/images/shop_04.png',
    description: 'AIR JORDAN LEGACY 312 LOW CHICAGO',
    color: const Color.fromARGB(255, 244, 168, 163),
    textDark: true,
    price: 140.00,
    rating: 4.0,
    sponsor: 'assets/images/nba2.png',
    size: 20,
  ),
  Product(
    id: '89005',
    title: 'NIKE AIR',
    image: 'assets/images/shop_05.png',
    description: 'NIKE AIR MORE UPTEMPO 96 ALTERNATES SPLIT',
    color: Colors.red,
    textDark: true,
    price: 165.00,
    rating: 2.0,
    sponsor: 'assets/images/nba2.png',
    size: 20,
  ),
  Product(
    id: '89006',
    title: 'AIR JORDAN 13',
    image: 'assets/images/shop_06.png',
    description: 'AIR JORDAN 13 RETRO BRAVE BLUE',
    color: Color.fromARGB(255, 3, 129, 226),
    textDark: false,
    price: 210.00,
    rating: 4.0,
    sponsor: 'assets/images/balle.png',
    size: 20,
  ),
  Product(
    id: '89007',
    title: 'AIR JORDAN 11',
    image: 'assets/images/shop_07.png',
    description: 'AIR JORDAN 11 CMFT LOW UNIVERSITY RED',
    color: Colors.red,
    textDark: true,
    price: 125.00,
    rating: 4.0,
    sponsor: 'assets/images/balle.png',
    size: 20,
  ),
  Product(
    id: '89008',
    title: 'JORDAN POINT',
    image: 'assets/images/shop_08.png',
    description: 'JORDAN POINT LANE FIREBERRY',
    color: const Color.fromARGB(255, 234, 234, 234),
    textDark: true,
    price: 140.00,
    rating: 4.0,
    sponsor: 'assets/images/nba2.png',
    size: 20,
  ),
  Product(
    id: '89009',
    title: 'AIR JORDAN 1 ZOOM',
    image: 'assets/images/shop_09.png',
    description: 'AIR JORDAN 1 ZOOM AIR COMFORT CRATER PURPLE',
    color: Colors.purple,
    textDark: false,
    price: 150.00,
    rating: 4.0,
    sponsor: 'assets/images/nba2.png',
    size: 20,
  ),
  Product(
    id: '89010',
    title: 'JORDAN DELTA 2',
    image: 'assets/images/shop_10.png',
    description: 'JORDAN DELTA 2 HASTA/BLACK',
    color: const Color.fromARGB(255, 58, 58, 58),
    textDark: false,
    price: 130.00,
    rating: 3.4,
    sponsor: 'assets/images/nba2.png',
    size: 20,
  ),
  Product(
    id: '89011',
    title: 'AIR JORDAN 1',
    image: 'assets/images/shop_11.png',
    description: 'AIR JORDAN 1 ELEMENT GORE-TEX LIGHT CURRY',
    color: const Color.fromARGB(255, 243, 182, 2),
    textDark: false,
    price: 180.00,
    rating: 2.8,
    sponsor: 'assets/images/nba2.png',
    size: 20,
  ),
  Product(
    id: '89012',
    title: 'AIR JORDAN 1',
    image: 'assets/images/shop_12.png',
    description: 'AIR JORDAN 1 ZOOM AIR COMFORT PUMPKIN SPICE',
    color: const Color.fromARGB(255, 183, 177, 18),
    textDark: false,
    price: 150.00,
    rating: 3.5,
    sponsor: 'assets/images/nba2.png',
    size: 20,
  ),
  Product(
    id: '89013',
    title: 'AIR JORDAN 1',
    image: 'assets/images/shop_13.png',
    description: 'AIR JORDAN 1 ELEMENT GORE-TEX BLACK',
    color: Colors.grey,
    textDark: false,
    price: 180.00,
    rating: 4.5,
    sponsor: 'assets/images/nba2.png',
    size: 20,
  ),
  Product(
    id: '89014',
    title: 'NIKE LEBRON 9',
    image: 'assets/images/shop_14.png',
    description: 'NIKE LEBRON 9 BIG BANG',
    color: Colors.orange,
    textDark: false,
    price: 240.00,
    rating: 4.8,
    sponsor: 'assets/images/balle.png',
    size: 20,
  ),
];
